### ISSUE TITLE
No loader is configured for ".scss" files: node_modules/../xxx.scss

### ISSUE THREAD

**Issue by zhubinda** [fz6m/cra-with-mfsu#3]
Unable to resolve the sass file in the dependency
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/86275412/217210702-5c43a3c1-5ed6-40b2-8c0f-daf448c98281.png">

**Comment by fz6m** [comment]
第三方包必须是规范的，只能有 css 。

**Comment by zhubinda** [comment]
> 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/86275412/217712021-08fe5467-dd36-4c82-a0e8-a2c46a7c358a.png">

webpack.config中babel-plugin-import来引入antd样式时会有以下报错（antd版本4.16.13）

![image](https://user-images.githubusercontent.com/86275412/217712185-0f740564-d9ef-4b43-8adb-eb61b40b84c2.png)

这需要做怎样的配置处理，难道要手动引入样式吗

**Comment by fz6m** [comment]
在开发的时候不需要使用按需 antd 插件，仅生产构建的时候再加入这个插件。

开发时，样式可以通过 less-loader 、babel 插件等手段添加 `antd/dist/antd.less` or `antd/dist/antd.min.css` 全量样式。

**Comment by zhubinda** [comment]
<img width="779" alt="image" src="https://user-images.githubusercontent.com/86275412/218060054-49f75f7e-2998-43ba-bed6-d2933288b0b2.png">
大佬，这边为什么要将shared的依赖也不被 MFSU 处理，react，react-router，antd等依赖不配置shared会报错，配置shared后不被MFSU处理，构建速度就不会很显著

**Comment by fz6m** [comment]
这个 shared 是 eager 需要的，独立使用的时候用不到的，独立使用 mfsu 仅限于 esbuild 。
